### ISSUE TITLE
how to build a JTabbedPane alternative?

### ISSUE THREAD

**Issue by tombrus** [HTTP-RPC/Sierra#13]
I was staring out to have a go and reimplement one of my IntelliJ forms with this.
My top element is a **JTabbedPane**... how can I make that in Sierra?

**Comment by gk-brown** [comment]
You could potentially do this with a combination of row, column, and stack panels, but you wouldn't get scrolling tabs and you'd have to manage the visibility of component's in the stack pane yourself (i.e. make only the selected tab component visible):

```java
column(
    row(
        cell(new JButton("A")),
        cell(new JButton("B")),
        cell(new JButton("C")),
        glue()
    ),
    stack(
        cell(new JButton("a")),
        cell(new JButton("b")),
        cell(new JButton("c"))
    ).weightBy(1.0)
)
```

**Comment by tombrus** [comment]
Thanks Greg!

> Any reason not to just use JTabbedPane? You could certainly use Sierra to lay out the contents of each tab.
eh, no, lol, I just do not know how to put a plain JXXX component in the hierarchy and continue using Sierra inside it. I did not find any examples of this (did I miss it?). Maybe you can add an example/test that shows this.

**Comment by gk-brown** [comment]
All of Sierra's layout panels ultimately extend `JPanel`, so you can use them like any other component. 

The factory methods in `UIBuilder` all return an instance of `UIBuilder.Cell`, but you can get the cell's component by calling `UIBuilder.Cell#getComponent()`. For example:

https://github.com/HTTP-RPC/Sierra/blob/master/sierra-test/src/main/java/org/httprpc/sierra/GreetingTest.java

**Comment by gk-brown** [comment]
Another example that might help is the periodic table test:

https://github.com/HTTP-RPC/Sierra/blob/master/sierra-test/src/main/java/org/httprpc/sierra/PeriodicTableTest.java

The `ElementPanel` and `KeyPanel` classes both extend `ColumnPanel` (which again is ultimately just a specialized `JPanel`). In other words, you're not required to use the factory methods to work with the layout panels - you can instantiate and manage them directly, as you would with any other component.

**Comment by gk-brown** [comment]
I added a description of `getComponent()` to the README. Hopefully this will help future readers.

**Comment by tombrus** [comment]
Great Greg, thanks!

I know from my own experience that sometimes these things seem pretty obvious when your head is in the code. For an outsider (and after a few years not looking at your own code!!) it is less obvious.... 

Anyway, I like the idea a lot and I would like to replace my usages of the IntelliJ form painter with your work so I can reduce dependencies on custom 'things' during builds. So keep it up!

**Comment by gk-brown** [comment]
Glad to hear that you are finding it useful. Please feel free to post any additional questions you have.
