### ISSUE TITLE
DatePicker: monthSpinner not working

### ISSUE THREAD

**Issue by folkfreund** [HTTP-RPC/Sierra#23]
Thanks for your project! I was looking for a simple DatePicker, and this seems to be a nice one :-)

But: the monthSpinner in the popup does not work. It seems, that the text of spinner's textField cannot be selected.

Can be reproduced with DateTimePickerTest

**Comment by gk-brown** [comment]
Thanks, I will take a look. In the meantime, could you update your PR to use spaces instead of tabs?

**Comment by gk-brown** [comment]
I ran the date picker test with your updates, and everything appears to work OK. However, the text of the spinner is still not selectable - I'm not sure what behavior you were expecting.

Either way, I think this is a good fix to apply because it resolves the focus issue you mentioned in the PR.

**Comment by folkfreund** [comment]
Thanks for your comments.
I understood, you want to keep the focus at the textfield. I know, that the spinner usually works on the selected part of the text, so it could also increment/decrement the year if selected. But moving the focus to the spinner would break the general behaviour to open the popup, whenever the textfield gets the focus. You could add a button (like in comboboxes) to open the popup. But automatic closing is very difficult then. And this approach might conflict with other pickers, like TimePicker, which do not use editable elements.
I suggest to keep it this way.

I'll prepare the requested changes when I'm back on my machine on monday.

**Comment by gk-brown** [comment]
This change has been merged to master.

**Comment by gk-brown** [comment]
This has been released. @folkfreund thank you for your help!
